// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stlr_bihash();
RcppExport SEXP _rcpp_module_boot_stlr_deque();
RcppExport SEXP _rcpp_module_boot_stlr_multiset();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stlr_bihash", (DL_FUNC) &_rcpp_module_boot_stlr_bihash, 0},
    {"_rcpp_module_boot_stlr_deque", (DL_FUNC) &_rcpp_module_boot_stlr_deque, 0},
    {"_rcpp_module_boot_stlr_multiset", (DL_FUNC) &_rcpp_module_boot_stlr_multiset, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_stlr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
